name: benchmark
version: 0.1.0

homepage: https://github.com/renggli/dart-benchmark
description: A time and space efficient collection of data structures and
  algorithms to deal with data in Dart.

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  data: ^0.10.0
  meta: ^1.8.0
  more: ^3.8.0
dev_dependencies:
  collection: ^1.16.0
  lints: ^2.0.0
  test: ^1.21.0
