name: benchmark
version: 0.1.0

homepage: https://github.com/renggli/dart-benchmark
description: A time and space efficient collection of data structures and
  algorithms to deal with data in Dart.

environment:
  sdk: ^3.8.0
dependencies:
  characters: ^1.3.0
  collection: ^1.19.0
  data: ^0.15.0
  meta: ^1.16.0
  more: ^4.3.0
  petitparser: ^7.0.0
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
